config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :orden_productos
  resources :proveedors
  get 'chatbot/index'
  resources :productos
  resources :pedidos
  resource :chat_responses, only: [:show]

  devise_for :usuarios, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :usuarios
  get 'home/menu'
  get 'home/about'
  get 'home/faq'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'


  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/proveedor.rb
class Proveedor < ApplicationRecord
    has_many :producto

    before_create :set_next_id
    after_destroy :rearrange_ids
    private

    def set_next_id
        max_id = Proveedor.maximum(:proveedor_id)
        self.proveedor_id = max_id ? max_id + 1 : 1
      end
    
      def rearrange_ids
        proveedor = Proveedor.order(:proveedor_id)
        proveedor.each_with_index do |proveedor, index|
          proveedor.update_column(:proveedor_id, index + 1)
        end
      end
end

app/controllers/proveedors_controller.rb
class ProveedorsController < ApplicationController
  before_action :set_proveedor, only: %i[ show edit update destroy ]

  # GET /proveedors or /proveedors.json
  def index
    @proveedors = Proveedor.all
  end

  # GET /proveedors/1 or /proveedors/1.json
  def show
    @productos = @proveedor.producto
    @pedidos = current_usuario.pedido.order(:id) # Ordena los pedidos por ID

  end

  # GET /proveedors/new
  def new
    @proveedor = Proveedor.new
  end

  # GET /proveedors/1/edit
  def edit
  end

  # POST /proveedors or /proveedors.json
  def create
    @proveedor = Proveedor.new(proveedor_params)

    respond_to do |format|
      if @proveedor.save
        format.html { redirect_to proveedor_url(@proveedor), notice: "Proveedor was successfully created." }
        format.json { render :show, status: :created, location: @proveedor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proveedors/1 or /proveedors/1.json
  def update
    respond_to do |format|
      if @proveedor.update(proveedor_params)
        format.html { redirect_to proveedor_url(@proveedor), notice: "Proveedor was successfully updated." }
        format.json { render :show, status: :ok, location: @proveedor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveedors/1 or /proveedors/1.json
  def destroy
    @proveedor.destroy!

    respond_to do |format|
      format.html { redirect_to proveedors_url, notice: "Proveedor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proveedor
      @proveedor = Proveedor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proveedor_params
      params.require(:proveedor).permit(:proveedor_id, :nombre, :telefono, :direccion, :correo, :apellido_paterno, :apellido_materno)
    end
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/views/proveedors/_form.html.erb
<%= form_with(model: proveedor) do |form| %>
  <% if proveedor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(proveedor.errors.count, "error") %> prohibited this proveedor from being saved:</h2>

      <ul>
        <% proveedor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3" style="width: 18rem;">
  <label class="form-label">Id del proveedor</label>
  <input class="form-control" placeholder="ID del proveedor" type="number" name="proveedor[proveedor_id]" id="proveedor_proveedor_id" readonly value="<%= @proveedor.proveedor_id || Proveedor.maximum(:proveedor_id).to_i + 1 %>" />
  </div>

  <div class="mb-3">
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre, 
    class:"form-control",
      placeholder:"Nombre" %>
  </div>

  <div class="mb-3">
  <%= form.label :apellido_paterno, style: "display: block" %>
  <%= form.text_field :apellido_paterno, 
  class:"form-control",
    placeholder:"Apeliido paterno" %>
</div>

<div class="mb-3">
  <%= form.label :apellido_materno, style: "display: block" %>
  <%= form.text_field :apellido_materno, 
  class:"form-control",
    placeholder:"Apeliido materno" %>
</div>

  <div class="mb-3">
    <%= form.label :telefono, style: "display: block" %>
    <%= form.text_field :telefono, 
    class:"form-control",
      placeholder:"Telefono" %>
  </div>

  <div class="mb-3">
    <%= form.label :direccion, style: "display: block" %>
    <%= form.text_field :direccion, 
    class:"form-control",
      placeholder:"Direccion" %>
  </div>

  <div class="mb-3">
    <%= form.label :correo, style: "display: block" %>
    <%= form.text_field :correo, 
    class:"form-control",
      placeholder:"Correo" %>
  </div>

  <div class="mb-3">
    <%= form.submit class:'btn btn-secondary'%>
  </div>
<% end %>

app/views/proveedors/_pedido.html.erb
<div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-6 col-md-6">
                <h1 class="display-6 fw-bold pb-md-4">Pedidos encargados</h1>
            </div>
            <div class="col-12 col-sm-6 col-md-6 text-end" style="margin-bottom: 30px;">
                <%= link_to "Ver productos", productos_path, class: "btn btn-primary btn-lg" %>
            </div>
        </div>
        <div data-reflow-type="product-search">
        <div class="reflow-product-search">
            <div class="ref-input-wrapper"><input id="searchInput" class="ref-search" type="text" inputmode="search" placeholder="Busca pedidos" /><span class="ref-cancel-search" style="display: none;"></span></div>
            <div class="ref-button" type="submit" style="display: none;">Search</div>
        </div>
        <br/>
    </div>
        <div id="TableSorterCard" class="card">
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover"  id="pedidosTable">
                            <thead class="table-dark">
                                <tr>
                                    <th scope="col">Folio</th>
                                    <th scope="col">Nombre del producto</th>
                                    <th scope="col">Cantidad ordenada</th>
                                    <th scope="col">Cantidad en existencia</th>
                                    <th scope="col">Precio C/U.</th>
                                    <th scope="col">Cantidad a pagar</th>
                                    <th scope="col">Fecha Inicial</th>
                                    <th scope="col">Fecha de entrega</th>
                                    <th scope="col">ID del usuario</th>
                                    <th scope="col">Nombre del proveedor</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @pedidos.each do |pedido| %>
                                    <% if pedido.usuario == current_usuario && pedido.producto.proveedor.proveedor_id == @proveedor.proveedor_id%>
                                    <tr>
                                            <td><%= pedido.pedido_id %></td>
                                            <td><%= pedido.producto ? pedido.producto.nombre : 'Producto no disponible' %></td>
                                            <td><%= pedido.cantidad_ordenada %></td>
                                            <td><%= pedido.producto ? pedido.producto.inventario.existencias : 'N/A' %></td>
                                            <td><%= pedido.producto ? pedido.producto.precio : 'N/A' %></td>
                                            <td><%= @total_sum %></td>
                                            <td><%= pedido.fecha_inicial.strftime("%d/%m/%Y") %></td>
                                            <td><%= pedido.fecha_entrega.strftime("%d/%m/%Y") %></td>
                                            <td><%= pedido.usuario_id %></td>
                                            <td>
                                            <% if pedido.producto && pedido.producto.proveedor %>
                                              <%= pedido.producto.proveedor.nombre %>        
                                              <%= pedido.producto.proveedor.apellido_paterno %>
                                              <%= pedido.producto.proveedor.apellido_materno %>
                                            <% else %>
                                              Proveedor no disponible
                                            <% end %>
                                          </td>
                                          
                                            <td><%= link_to "Mostrar", pedido, class: "btn btn-dark" %></td>
                                            <td><%= button_to "Eliminar", pedido, method: :delete, form: { data: { turbo_confirm: '¿Estás seguro?' } }, class: "btn btn-danger" %></td>      
                                        </tr>
                                    <% end %>
                                <% end %>
                            </tbody>
                        </table>
            </div>
        </div>
    </div>

    <script>
    document.addEventListener('turbo:load', function() {
        const searchInput = document.getElementById('searchInput');
        const pedidosTable = document.getElementById('pedidosTable').getElementsByTagName('tbody')[0];
        const pedidos = Array.from(pedidosTable.getElementsByTagName('tr'));

        searchInput.addEventListener('input', function() {
            const searchString = searchInput.value.trim().toLowerCase();

            pedidos.forEach(function(pedido) {
                const nombreProducto = pedido.getElementsByTagName('td')[1].textContent.toLowerCase();
                const folioPedido = pedido.getElementsByTagName('td')[0].textContent.toLowerCase();
                if (nombreProducto.includes(searchString) || folioPedido.includes(searchString)) {
                    pedido.style.display = 'table-row';
                } else {
                    pedido.style.display = 'none';
                }
            });
        });
    });
</script>

app/views/proveedors/_producto.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-sm-6 col-md-6">
            <h1 class="display-6 fw-bold pb-md-4">Mis productos</h1>
        </div>
        <div class="col-12 col-sm-6 col-md-6 text-end" style="margin-bottom: 30px;">
            <%= link_to "Inventario", inventarios_path, class: "btn btn-primary btn-lg" %>
        </div>
    </div>
    <div data-reflow-type="product-search">
        <div class="reflow-product-search">
            <div class="ref-input-wrapper">
                <input id="searchInput" class="ref-search" type="text" inputmode="search" placeholder="Busca productos" />
                <span class="ref-cancel-search" style="display: none;"></span>
            </div>
            <div class="ref-button" type="submit" style="display: none;">Search</div>
        </div>
        <br/>
    </div>
    <div id="TableSorterCard" class="card">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table table-striped table-hover" id="productTable">
                        <thead class="table-dark">
                            <tr>
                                <th scope="col">ID del producto</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Precio (MXN)</th>
                                <th scope="col">Peso (gr)</th>
                                <th scope="col">Existencias</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @productos.each do |producto| %>
                            <tr>
                                <td><%= producto.producto_id %></td>
                                <td><%= producto.nombre %></td>
                                <td><%= producto.precio %></td>
                                <td><%= producto.peso %></td>
                                <td><%= producto.inventario.existencias %></td>
                                <td><%= link_to 'Agregar existencias', edit_inventario_path(producto.inventario), class: 'btn btn-secondary' %></td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('turbo:load', function() {
        const searchInput = document.getElementById('searchInput');
        const productTable = document.getElementById('productTable').getElementsByTagName('tbody')[0];
        const productos = Array.from(productTable.getElementsByTagName('tr'));

        searchInput.addEventListener('input', function() {
            const searchString = searchInput.value.trim().toLowerCase();

            productos.forEach(function(producto) {
                const nombre = producto.getElementsByTagName('td')[1].textContent.toLowerCase();
                const folioPedido = producto.getElementsByTagName('td')[0].textContent.toLowerCase();

                if (nombre.includes(searchString)|| folioPedido.includes(searchString)) {
                    producto.style.display = 'table-row';
                } else {
                    producto.style.display = 'none';
                }
            });
        });
    });
</script>

app/views/proveedors/_proveedor.html.erb
<div id="<%= dom_id proveedor %>">
  <p>
    <strong>Proveedor:</strong>
    <%= proveedor.proveedor_id %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= proveedor.nombre %>
  </p>

  <p>
    <strong>Telefono:</strong>
    <%= proveedor.telefono %>
  </p>

  <p>
    <strong>Direccion:</strong>
    <%= proveedor.direccion %>
  </p>

  <p>
    <strong>Correo:</strong>
    <%= proveedor.correo %>
  </p>

  <p>
    <strong>Apellido paterno:</strong>
    <%= proveedor.apellido_paterno %>
  </p>

  <p>
    <strong>Apellido materno:</strong>
    <%= proveedor.apellido_materno %>
  </p>

</div>

app/views/proveedors/edit.html.erb
<section class="py-4 py-md-5 my-5">

<h1 class="display-6 fw-bold pb-md-4">Editar proveedores</h1>

<%= render "form", proveedor: @proveedor %>

<br>

<div>
  <%= link_to "Mostrar a este proveedor", @proveedor %> |
  <%= link_to "Regresar", proveedors_path %>
</div>
</section>

app/views/proveedors/index.html.erb
<section class="py-5 mt-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-6 col-md-6">
                <h1 class="display-6 fw-bold pb-md-4">Lista de proveedores</h1>
            </div>
            <div class="col-12 col-sm-6 col-md-6 text-end" style="margin-bottom: 30px;">
                <%= link_to "Nuevo proveedor", new_proveedor_path, class: "btn btn-primary btn-lg" %>
                <%= link_to "Ver productos", productos_path, class: "btn btn-secondary btn-lg" %>
            </div>
        </div>
        <div class="reflow-product-search">
        <div class="ref-input-wrapper"><input id="searchInput" class="ref-search" type="text" inputmode="search" placeholder="Busca proveedor" /><span class="ref-cancel-search" style="display: none;"></span></div>
        <div class="ref-button" type="submit" style="display: none;">Search</div>
    </div>
        <div id="TableSorterCard" class="card">
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover" id="proveedorTable">
                            <thead class="table-dark">
                                <tr>
                                    <th scope="col">ID del proveedor</th>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Telefono</th>
                                    <th scope="col">Direccion</th>
                                    <th scope="col">Correo</th>
                                    <th scope="col">Nuevo producto</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @proveedors.each do |proveedor| %>
                                <tr>
                                    <td><%= proveedor.proveedor_id %></td>
                                    <td>
                                    <%= proveedor.nombre %>
                                    <%= proveedor.apellido_paterno %>
                                    <%= proveedor.apellido_materno %>
                                    </td>
                                    <td><%= proveedor.telefono %></td>
                                    <td><%= proveedor.direccion %></td>
                                    <td><%= proveedor.correo %></td>
                                    <td><%= link_to "Nuevo", new_producto_path(proveedor_id: proveedor.id), class: "btn btn-success" %></td>
                                    <td><%= link_to 'Mostrar', proveedor, class: 'btn btn-dark' %></td>
                                    <td><%= link_to 'Editar', edit_proveedor_path(proveedor), class: 'btn btn-secondary' %></td>
                                    <td><%= button_to 'Eliminar', proveedor, method: :delete, form: { data: { turbo_confirm: '¿Estás seguro?' } }, class: 'btn btn-danger' %></td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    document.addEventListener('turbo:load', function() {
        const searchInput = document.getElementById('searchInput');
        const proveedorTable = document.getElementById('proveedorTable').getElementsByTagName('tbody')[0];
        const proveedors = Array.from(proveedorTable.getElementsByTagName('tr'));

        searchInput.addEventListener('input', function() {
            const searchString = searchInput.value.trim().toLowerCase();

            proveedors.forEach(function(proveedor) {
                const nombreProveedor = proveedor.getElementsByTagName('td')[1].textContent.toLowerCase();
                const folioProveedor = proveedor.getElementsByTagName('td')[0].textContent.toLowerCase();
                if (nombreProveedor.includes(searchString) || folioProveedor.includes(searchString)) {
                    proveedor.style.display = 'table-row';
                } else {
                    proveedor.style.display = 'none';
                }
            });
        });
    });
</script>

app/views/proveedors/new.html.erb
<section class="py-4 py-md-5 my-5">

<h1 class="display-6 fw-bold pb-md-4">Crear proveedor</h1>

<%= render "form", proveedor: @proveedor %>

<br>

<div>
  <%= link_to "Regresar", proveedors_path %>
</div>
</section>

app/views/proveedors/show.html.erb
<section class="py-5">
<div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">
        <%= @proveedor.nombre %>
        <%= @proveedor.apellido_paterno %>
        <%= @proveedor.apellido_materno %>
        </h1>
        <p class="col-md-8 fs-4"><strong>Correo:</strong> <%= @proveedor.correo %></p>
        <p class="col-md-8 fs-4"><strong>Teléfono:</strong> <%= @proveedor.telefono %></p>
        <p class="col-md-8 fs-4"><strong>Direccion:</strong> <%= @proveedor.direccion %></p>
        <p class="col-md-8 fs-4"><strong>Id del proveedor:</strong> <%= @proveedor.proveedor_id %></p>
        
        <%= link_to "Regresa", proveedors_path, class: "btn btn-secondary" %>
        </div>
    </div>
    <div class="cliente-info">


  </div>
  <%= render 'producto' %>
  </br>
  <%= render 'pedido' %>

  </section>