config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :orden_productos
  resources :proveedors
  get 'chatbot/index'
  resources :productos
  resources :pedidos
  resource :chat_responses, only: [:show]

  devise_for :usuarios, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :usuarios
  get 'home/menu'
  get 'home/about'
  get 'home/faq'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'


  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  def about
  end
  def menu
  end
  def faq
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer>
    <div class="container py-4 py-lg-5">
        <div class="row row-cols-2 row-cols-md-4">
            <div class="col-12 col-md-3 col-xl-4">
                <div class="fw-bold d-flex align-items-center mb-2"><span>Nutricel</span></div>
                <p class="text-muted">Nutriendo tu vida, célula a célula.</p>
            </div>
            <div class="col-sm-4 col-md-3 col-xl-4 text-lg-start d-flex flex-column">
                <h3 class="fs-6 fw-bold">Servicios</h3>
                <ul class="list-unstyled">
                    <li><%= link_to 'Productos', productos_path, class:"nav-link" %></li>
                    <li><%= link_to 'Pedidos', pedidos_path, class:"nav-link" %></li>
                    <li><%= link_to 'Proveedores', proveedors_path, class:"nav-link" %></li>
                </ul>
            </div>
            <div class="col-sm-4 col-md-3 text-lg-start d-flex flex-column">
                <h3 class="fs-6 fw-bold">Acerca de</h3>
                <ul class="list-unstyled">
                    <li><%= link_to 'Compañia', home_about_path, class:"nav-link" %></li>
                    <li><%= link_to 'FAQ', home_faq_path, class:"nav-link" %></li>
                    <li></li>
                </ul>
            </div>
        </div>
        <hr />
        <div class="text-muted d-flex justify-content-between align-items-center pt-3">
            <p class="mb-0">Copyright © 2024 Nutricel</p>
            <ul class="list-inline mb-0">
                <li class="list-inline-item"><svg class="bi bi-facebook" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"></path>
                    </svg></li>
                <li class="list-inline-item"><svg class="bi bi-twitter" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15"></path>
                    </svg></li>
                <li class="list-inline-item"><svg class="bi bi-instagram" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"></path>
                    </svg></li>
            </ul>
        </div>
    </div>
</footer>

app/views/home/_header.html.erb
<nav id="mainNav" class="navbar navbar-expand-md fixed-top navbar-shrink py-3 navbar-light">
    <div class="container"><a class="navbar-brand d-flex align-items-center" href="/"><span>Nutricel</span></a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
        <div id="navcol-1" class="collapse navbar-collapse">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item"> <%= link_to 'Inicio', root_path, class:"nav-link" %></li>
                <li class="nav-item"><%= link_to 'Menu', home_menu_path, class:"nav-link" %></li>
                <li class="nav-item"><%= link_to 'Chatbot', chatbot_index_path, class:"nav-link" %></li>
                <li class="nav-item"><%= link_to 'FAQ', home_faq_path, class:"nav-link" %></li>
                <li class="nav-item"><%= link_to 'Acerca de', home_about_path, class:"nav-link" %></li>
            </ul>
            <% if usuario_signed_in? %>
            <%= link_to 'Cerrar sesion', destroy_usuario_session_path, 'data-turbo-method': :delete, class: "btn btn-primary shadow", role: "button" %>
            <% else %>
            <%= link_to 'Iniciar sesion', new_usuario_session_path, class: "btn btn-primary shadow", role: "button" %>
            <% end %>
        </div>
    </div>
</nav>

app/views/home/index.html.erb
<html data-bs-theme="light" lang="en" style>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>Home - Nutricel</title>
</head>

<body>
    <header class="pt-5">
        <div class="container pt-4 pt-xl-5">
            <div class="row pt-5">
                <div class="col-md-8 text-center text-md-start mx-auto">
                    <div class="text-center">
                        <h1 class="display-4 fw-bold mb-5">Nutriendo tu vida, célula a <span class="underline">célula</span>.</h1>
                    </div>
                </div>
                <div class="col-12 col-lg-10 mx-auto">
                    <div class="text-center position-relative"><%= image_tag("illustrations/meeting.svg", class: "img-fluid w-100") %></div>
                </div>
            </div>
        </div>
    </header>
    <!--Seccion Inicial -->
    <section>
        <div class="container py-4 py-xl-5">
            <div class="row gy-4 row-cols-1 row-cols-md-2 row-cols-lg-3">
                <div class="col">
                    <div class="card border-light border-1 d-flex justify-content-center p-4">
                        <div class="card-body">
                            <div class="bs-icon-lg bs-icon-rounded bs-icon-secondary d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block mb-4 bs-icon"> 
                            <svg class="icon icon-tabler icon-tabler-shopping-cart" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M6 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path>
                            <path d="M17 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path>
                            <path d="M17 17h-11v-14h-2"></path>
                            <path d="M6 5l14 1l-1 7h-13"></path>
                        </svg>
                        </div>
                            <div>
                                <h4 class="fw-bold">Productos</h4>
                                <p class="text-muted">Descubre nuestra selección completa de artículos.</p><%= link_to 'Ir a productos', productos_path, class:"nav-link" %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card border-light border-1 d-flex justify-content-center p-4">
                        <div class="card-body">
                            <div class="bs-icon-lg bs-icon-rounded bs-icon-secondary d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block mb-4 bs-icon">
                            <svg class="icon icon-tabler icon-tabler-shopping-cart-search" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M4 19a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path>
                            <path d="M11 17h-5v-14h-2"></path>
                            <path d="M6 5l14 1l-.718 5.023m-6.282 1.977h-7"></path>
                            <path d="M18 18m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
                            <path d="M20.2 20.2l1.8 1.8"></path>
                        </svg>

                            
                                </div>
                            <div>
                                <h4 class="fw-bold">Pedidos</h4>
                                <p class="text-muted">Gestiona y realiza seguimiento de todas tus pedidos.</p><%= link_to 'Ir a pedidos', pedidos_path, class:"nav-link" %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card border-light border-1 d-flex justify-content-center p-4">
                        <div class="card-body">
                            <div class="bs-icon-lg bs-icon-rounded bs-icon-secondary d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block mb-4 bs-icon">                            
                            <svg class="icon icon-tabler icon-tabler-users" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M9 7m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path>
                            <path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
                            <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                            <path d="M21 21v-2a4 4 0 0 0 -3 -3.85"></path>
                            </svg>
                            </div>
                            <div>
                                <h4 class="fw-bold">Clientes</h4>
                                <p class="text-muted">Accede a la lista de usuarios registrados.</p><%= link_to 'Ir a usuarios', usuarios_path, class:"nav-link" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Consulta medica-->
    <section class="py-4 py-xl-5">
        <div class="container">
            <div class="bg-primary border rounded border-0 border-primary overflow-hidden">
                <div class="row g-0">
                    <div class="col-md-6 d-flex flex-column justify-content-center">
                        <div class="text-white p-4 p-md-5">
                            <h2 class="fw-bold mb-3">Consulta medica</h2>
                            <p class="mb-4">Genera una consulta medica con uno de nuestros medicos certificados.</p>
                            <div class="my-3"><a class="btn btn-secondary me-2 mt-2" role="button" href="#">Ir a consultas</a></div>
                        </div>
                    </div>
                    <div class="col-md-6 order-first order-md-last" style="min-height: 250px;"><%= image_tag("illustrations/web-development.svg", class: "img-fluid w-100") %></div>
                </div>
            </div>
        </div>
    </section>
    <!--Plan nutricional -->
    <section>
        <div class="container py-4 py-xl-5">
            <div class="row">
                <div class="col-md-6">
                    <h3 class="display-6 fw-bold pb-md-4">Ventajas de usar un plan <span class="underline">nutricional</span></h3>
                </div>
                <div class="col-md-6 pt-4">
                    <p class="text-muted mb-4"></p>
                </div>
            </div>
            <div class="row gy-4 gy-md-0">
                <div class="col-md-6 d-flex d-sm-flex d-md-flex justify-content-center align-items-center justify-content-md-start align-items-md-center justify-content-xl-center">
                    <div>
                        <div class="row gy-2 row-cols-1 row-cols-sm-2">
                            <div class="col text-center text-md-start">
                                <div class="d-flex justify-content-center align-items-center justify-content-md-start"><svg class="icon icon-tabler icon-tabler-sun fs-3 text-primary bg-secondary" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                        <path d="M12 12m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path>
                                        <path d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7"></path>
                                    </svg>
                                    <h5 class="fw-bold mb-0 ms-2">Personalizado</h5>
                                </div>
                                <p class="text-muted my-3">Adaptado a tus necesidades específicas.</p>
                            </div>
                            <div class="col text-center text-md-start">
                                <div class="d-flex justify-content-center align-items-center justify-content-md-start"><svg class="icon icon-tabler icon-tabler-sun fs-3 text-primary bg-secondary" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                        <path d="M12 12m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path>
                                        <path d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7"></path>
                                    </svg>
                                    <h5 class="fw-bold mb-0 ms-2">Equilibrado</h5>
                                </div>
                                <p class="text-muted my-3">Asegura una dieta nutritiva y balanceada.</p>
                            </div>
                            <div class="col text-center text-md-start">
                                <div class="d-flex justify-content-center align-items-center justify-content-md-start"><svg class="icon icon-tabler icon-tabler-sun fs-3 text-primary bg-secondary" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                        <path d="M12 12m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path>
                                        <path d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7"></path>
                                    </svg>
                                    <h5 class="fw-bold mb-0 ms-2">Control de peso</h5>
                                </div>
                                <p class="text-muted my-3">Ayuda en la gestión del peso de manera saludable.</p>
                            </div>
                            <div class="col text-center text-md-start">
                                <div class="d-flex justify-content-center align-items-center justify-content-md-start"><svg class="icon icon-tabler icon-tabler-sun fs-3 text-primary bg-secondary" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                        <path d="M12 12m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path>
                                        <path d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7"></path>
                                    </svg>
                                    <h5 class="fw-bold mb-0 ms-2">Mejora de la salud</h5>
                                </div>
                                <p class="text-muted my-3">Reduce el riesgo de enfermedades crónicas.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 order-first order-md-last">
                    <div><%= image_tag("illustrations/teamwork.svg", class: "img-fluid w-100") %></div>
                </div>
            </div>
        </div>
    </section>
    <!--Contacto -->
    <section class="py-4 py-xl-5">
        <div class="container">
            <div class="text-white bg-primary border rounded border-0 border-primary d-flex flex-column justify-content-between flex-lg-row p-4 p-md-5">
                <div class="pb-2 pb-lg-1">
                    <h2 class="fw-bold text-secondary mb-2">¿No estás seguro de qué plan te conviene?</h2>
                    <p class="mb-0">Realizale preguntas a nuestro chatbot</p>
                </div>
                <div class="my-2">
                <%= link_to 'Chatbot', chatbot_index_path, class: "btn btn-light fs-5 py-2 px-4" %>
                </div
            </div>
        </div>
    </section>
</body>

</html>

app/views/home/menu.html.erb
<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-4 mb-5"><%= image_tag("illustrations/presentation-2.svg", class: "img-fluid w-100") %></div>
            <div class="col d-md-flex align-items-md-end align-items-lg-center mb-5">
                <div class="row gy-4 row-cols-1 row-cols-md-2 flex-grow-1">
                    <div class="col">
                        <div class="card border-light border-1 d-flex justify-content-center p-4">
                            <div class="card-body">
                                <div>
                                <h4 class="fw-bold">Productos</h4>
                                <p class="text-muted d-none d-xl-block">Descubre nuestra selección completa de artículos.</p>
                                <%= link_to 'Ir a productos', productos_path, class:"nav-link" %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card border-light border-1 d-flex justify-content-center p-4">
                            <div class="card-body">
                                <div>
                                    <h4 class="fw-bold">Pedidos</h4>
                                    <p class="text-muted d-none d-xl-block">Gestiona y realiza seguimiento de todas tus pedidos.</p>
                                    <%= link_to 'Ir a pedidos', pedidos_path, class:"nav-link" %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
        <div class="col d-md-flex align-items-md-end align-items-lg-center mb-5">
            <div class="row gy-4 row-cols-1 row-cols-md-2 flex-grow-1">
                <div class="col">
                    <div class="card border-light border-1 d-flex justify-content-center p-4">
                        <div class="card-body">
                            <div>
                            <h4 class="fw-bold">Usuarios</h4>
                            <p class="text-muted d-none d-xl-block">Accede a la lista de usuarios registrados.</p>
                            <%= link_to 'Ir a usuarios', usuarios_path, class:"nav-link" %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card border-light border-1 d-flex justify-content-center p-4">
                        <div class="card-body">
                            <div>
                                <h4 class="fw-bold">Editar perfil</h4>
                                <p class="text-muted d-none d-xl-block">Realiza cambios y ajustes en tu información personal.</p>
                                <%= link_to 'Ir a editar perfil', edit_usuario_registration_path, class:"nav-link" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 order-first order-md-last mb-5"><%= image_tag("illustrations/video-call.svg", class: "img-fluid w-100") %></div>
    </div>

        <div class="row">
        <div class="col-md-4 mb-5"><%= image_tag("illustrations/presentation-2.svg", class: "img-fluid w-100") %></div>
            <div class="col d-md-flex align-items-md-end align-items-lg-center mb-5">
                <div class="row gy-4 row-cols-1 row-cols-md-2 flex-grow-1">
                    <div class="col">
                        <div class="card border-light border-1 d-flex justify-content-center p-4">
                            <div class="card-body">
                                <div>
                                <h4 class="fw-bold">Proveedores</h4>
                                <p class="text-muted d-none d-xl-block">Accede a la lista de proveedores registrados.</p>
                                <%= link_to 'Ir a proveedores', proveedors_path, class:"nav-link" %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card border-light border-1 d-flex justify-content-center p-4">
                            <div class="card-body">
                                <div>
                                    <h4 class="fw-bold">Inventario</h4>
                                    <p class="text-muted d-none d-xl-block">Ve los registros del inventario</p>
                                    <%= link_to 'Ir a inventario', inventarios_path, class:"nav-link" %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>