config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :orden_productos
  resources :proveedors
  get 'chatbot/index'
  resources :productos
  resources :pedidos
  resource :chat_responses, only: [:show]

  devise_for :usuarios, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :usuarios
  get 'home/menu'
  get 'home/about'
  get 'home/faq'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'


  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/producto.rb
class Producto < ApplicationRecord
    has_many :pedido
    belongs_to :proveedor
    has_many :inventario
  
  
    before_create :set_next_id
    after_destroy :rearrange_ids

    has_one :inventario, dependent: :destroy
    after_create :create_inventario_record  
    private
  
    def create_inventario_record
      create_inventario(existencias: 0) 
    end

    def set_next_id
      max_id = Producto.maximum(:producto_id)
      self.producto_id = max_id ? max_id + 1 : 1
    end
  
    def rearrange_ids
      productos = Producto.order(:producto_id)
      productos.each_with_index do |producto, index|
        producto.update_column(:producto_id, index + 1)
      end
    end

  end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: %i[ show edit update destroy ]
  before_action :authenticate_usuario!

  # GET /productos or /productos.json
  def index
    @productos = Producto.all
  end
  
  # GET /productos/1 or /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  
    puts "Proveedor ID: #{params[:proveedor_id]}" # Agrega esta línea
  
    @proveedor = Proveedor.find(params[:proveedor_id]) 
    @producto.proveedor = @proveedor
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos or /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to producto_url(@producto), notice: "Producto was successfully created." }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1 or /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to producto_url(@producto), notice: "Producto was successfully updated." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1 or /productos/1.json
  def destroy
    @producto.destroy!

    respond_to do |format|
      format.html { redirect_to productos_url, notice: "Producto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producto_params
      params.require(:producto).permit(:producto_id, :nombre, :precio, :peso, :imagen, :fecha_expiracion, :proveedor_id)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_with(model: producto) do |form| %>
  <% if producto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
        <% producto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3" style="width: 18rem;">
  <label class="form-label">Id del Producto</label>
  <input class="form-control" placeholder="ID del producto" type="number" name="producto[producto_id]" id="producto_producto_id" readonly value="<%= @producto.producto_id || Producto.maximum(:producto_id).to_i + 1 %>" />
  </div>

  <% if @proveedor %>
    <div class="mb-3" style="width: 18rem;">
      <label class="form-label">Proveedor</label>
      <input type="hidden" name="producto[proveedor_id]" value="<%= @proveedor.id %>">
      <input class="form-control" type="text" value="<%= @proveedor.nombre %>" readonly>
    </div>
  <% end %>



  <div class="mb-3" style="width: 18rem;">
    <input class="form-control" placeholder="Nombre" type="text" name="producto[nombre]" id="producto_nombre" />
  </div>

  
  <div class="mb-3" style="width: 18rem;">
    <input class="form-control" placeholder="Precio" type="text" name="producto[precio]" id="producto_precio" />
  </div>

  <div class="mb-3" style="width: 18rem;">
    <input class="form-control" placeholder="Peso" type="text" name="producto[peso]" id="producto_peso" />
  </div>

  <div class="mb-3" style="width: 18rem;">
    <input class="form-control" placeholder="Imagen" type="text" name="producto[imagen]" id="producto_imagen" />
  </div>

  <div class="mb-3" style="width: 18rem;">
  <%= form.label :fecha_expiracion, style: "display: block" %>
    <input class="form-control" type="datetime-local" name="producto[fecha_expiracion]" id="producto_fecha_expiracion" />
  </div>

  <div>
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/productos/_producto.html.erb
<div id="<%= dom_id producto %>">
  <p>
    <strong>Id producto:</strong>
    <%= producto.id_producto %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= producto.nombre %>
  </p>

  <p>
    <strong>Precio:</strong>
    <%= producto.precio %>
  </p>

  <p>
    <strong>Peso:</strong>
    <%= producto.peso %>
  </p>

  <p>
    <strong>Imagen:</strong>
    <%= producto.imagen %>
  </p>

  <p>
    <strong>Fecha expiracion:</strong>
    <%= producto.fecha_expiracion %>
  </p>

</div>

app/views/productos/edit.html.erb
<section class="py-5">
</br></br>
<h1>Editing producto</h1>

<%= render "form", producto: @producto %>

<br>

<div>
  <%= link_to "Show this producto", @producto %> |
  <%= link_to "Back to productos", productos_path %>
</div>
</section>

app/views/productos/index.html.erb
<section class="py-5 mt-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-6 col-md-6">
                <h1 class="display-6 fw-bold pb-md-4">Lista de productos</h1>
            </div>
            
            <div class="col-12 col-sm-6 col-md-6 text-end" style="margin-bottom: 30px;">
            <%= link_to "Mis pedidos", pedidos_path, class: "btn btn-primary btn-lg" %>
            <%= link_to "Inventario", inventarios_path, class: "btn btn-secondary btn-lg" %>
            </div>
        </div>
        <div data-reflow-type="product-search">
            <div class="reflow-product-search">
                <div class="ref-input-wrapper"><input id="searchInput" class="ref-search" type="text" inputmode="search" placeholder="Busca productos" /><span class="ref-cancel-search" style="display: none;"></span></div>
                <div class="ref-button" type="submit" style="display: none;">Search</div>
            </div>
            <br/>
        </div>
        <div id="TableSorterCard" class="card">
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover" id="productTable">
                            <thead class="table-dark">
                                <tr>
                                    <th scope="col">ID del producto</th>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Precio (MXN)</th>
                                    <th scope="col">Peso (gr)</th>
                                    <th scope="col">Existencias</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @productos.each do |producto| %>
                                <tr>
                                    <td><%= producto.producto_id %></td>
                                    <td><%= producto.nombre %></td>
                                    <td><%= producto.precio %></td>
                                    <td><%= producto.peso %></td>
                                    <td><%= producto.inventario ? producto.inventario.existencias : 'N/A' %></td>
                                    <td><%= link_to 'Comprar', new_pedido_path(producto_id: producto.id), class: 'btn btn-secondary' %></td>
                                    <td><%= link_to 'Mostrar', producto, class: 'btn btn-dark' %></td>
                                    <td><%= button_to 'Eliminar', producto, method: :delete, form: { data: { turbo_confirm: '¿Estás seguro?' } }, class: 'btn btn-danger' %></td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
document.addEventListener('turbo:load', function() {
    const searchInput = document.getElementById('searchInput');
    const productTable = document.getElementById('productTable').getElementsByTagName('tbody')[0];
    const productos = Array.from(productTable.getElementsByTagName('tr'));

    searchInput.addEventListener('input', function() {
        const searchString = searchInput.value.trim().toLowerCase();

        productos.forEach(function(producto) {
            const nombre = producto.getElementsByTagName('td')[1].textContent.toLowerCase();
            const folioProducto = producto.getElementsByTagName('td')[0].textContent.toLowerCase();

            if (nombre.includes(searchString) || folioProducto.includes(searchString)) {
                producto.style.display = 'table-row';
            } else {
                producto.style.display = 'none';
            }
        });
    });
});

</script>

app/views/productos/new.html.erb
<section class="py-5">
<h1 class="display-6 fw-bold pb-md-4">Nuevo producto</h1>
<%= render "form", producto: @producto %>

<br>

<div>
  <%= link_to "Regresar", proveedors_path ,class:"btn btn-dark"%>
</div>
</section>

app/views/productos/show.html.erb
<section class="py-5">
<div class="p-5 mb-4 bg-light rounded-3">
  <div style="display: grid; grid-template-columns: 1fr 1fr;">
    <div>      
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">
          Datos del producto
        </h1>
        <p class="col-md-8 fs-4"><strong>ID del producto:</strong> <%= @producto.producto_id %></p>
        <p class="col-md-8 fs-4"><strong>Nombre:</strong> <%= @producto.nombre %></p>
        <p class="col-md-8 fs-4"><strong>Precio (MXN):</strong> <%= @producto.precio %></p>
        <p class="col-md-8 fs-4"><strong>Peso (gr):</strong> <%= @producto.peso %></p> 
        <p class="col-md-8 fs-4"><strong>Existencias:</strong> <%= @producto.inventario.existencias %></p> 
        <p class="col-md-8 fs-4"><strong>Fecha de expiracion:</strong> <%= @producto.fecha_expiracion %></p> 
        <p class="col-md-8 fs-4"><strong>Proveedor asignado:</strong> <%= @producto.proveedor.nombre %></p> 

        </p>                   
       <%= link_to "Regresar", productos_path, class: "btn btn-dark btn-lg"%>
      </div>
    </div>
    <div>  
      </br></br>
      <p class="col-md-8 fs-4">
      <%  if File.exist?(Rails.root.join('app','assets', 'images', @producto.imagen)) %>
      <%= image_tag(@producto.imagen) %>
      <% end %>
      
    </div>
  </div>
</div>

<div class="producto-info">
</div>
</section>
  