config/routes.rb
Rails.application.routes.draw do
  resources :inventarios
  resources :orden_productos
  resources :proveedors
  get 'chatbot/index'
  resources :productos
  resources :pedidos
  resource :chat_responses, only: [:show]

  devise_for :usuarios, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :usuarios
  get 'home/menu'
  get 'home/about'
  get 'home/faq'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'


  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/inventario.rb
class Inventario < ApplicationRecord
    belongs_to :producto

    before_create :set_next_id
    after_destroy :rearrange_ids
    private

    def set_next_id
        max_id = Inventario.maximum(:inventario_id)
        self.inventario_id = max_id ? max_id + 1 : 1
      end
    
      def rearrange_ids
      inventario = Inventario.order(:inventario_id)
        inventario.each_with_index do |inventario, index|
          inventario.update_column(:inventario_id, index + 1)
        end
      end
end

app/controllers/inventarios_controller.rb
class InventariosController < ApplicationController
  before_action :set_inventario, only: %i[ show edit update destroy ]

  # GET /inventarios or /inventarios.json
  def index
    @inventarios = Inventario.all
  end

  # GET /inventarios/1 or /inventarios/1.json
  def show
  end

  # GET /inventarios/new
  def new
    @inventario = Inventario.new
  end

  # GET /inventarios/1/edit
  def edit
    @producto = @inventario.producto

    @inventario = Inventario.find(params[:id])
    @proveedor = @inventario.producto.proveedor
    
  end

  # POST /inventarios or /inventarios.json
  def create
    @inventario = Inventario.new(inventario_params)

    respond_to do |format|
      if @inventario.save
        format.html { redirect_to inventario_url(@inventario), notice: "Inventario was successfully created." }
        format.json { render :show, status: :created, location: @inventario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventarios/1 or /inventarios/1.json
  def update
    respond_to do |format|
      # Obtenemos el valor actual de existencias
      existencias_actuales = @inventario.existencias
      # Sumamos las existencias actuales con el valor proporcionado por el usuario
      @inventario.existencias = existencias_actuales + inventario_params[:existencias].to_i
  
      if @inventario.save
        format.html { redirect_to proveedor_path(@inventario.producto.proveedor), notice: "El inventario fue actualizado exitosamente." }
        format.json { render :show, status: :ok, location: @inventario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventario.errors, status: :unprocessable_entity }
      end
    end
  end
  
  

  # DELETE /inventarios/1 or /inventarios/1.json
  def destroy
    @inventario.destroy!

    respond_to do |format|
      format.html { redirect_to inventarios_url, notice: "Inventario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventario
      @inventario = Inventario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventario_params
      params.require(:inventario).permit(:inventario_id, :existencias, :producto_id)
    end
end

app/helpers/inventarios_helper.rb
module InventariosHelper
end

app/views/inventarios/_form.html.erb
<%= form_with(model: inventario) do |form| %>
  <% if inventario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventario.errors.count, "error") %> prohibited this inventario from being saved:</h2>

      <ul>
        <% inventario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :inventario_id, style: "display: block" %>
    <%= form.text_field :inventario_id ,
    class:"form-control",
    placeholder:"Id del inventario",
    readonly: true%>
  </div>
  <div class="mb-3">
    <%= form.label :nombre, "Nombre del producto", style: "display: block" %>
    <input type="text" 
           class="form-control" 
           value="<%= @producto.nombre %>" 
           readonly>
  </div>

  <div class="mb-3">
  <%= form.label :existencias, "Existencias", style: "display: block" %>
  <%= form.number_field :existencias, class: "form-control", 
  value: 0,
  placeholder: "Existencias a agregar" %>
  </div>

  <div class="mb-3">
    <%= form.label :producto_id, "ID del Producto", style: "display: block" %>
    <input type="text" 
           class="form-control" 
           value="<%= @producto.producto_id %>" 
           readonly>
  </div>

  <div class="mb-3">
    <%= form.submit class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/inventarios/_inventario.html.erb
<div id="<%= dom_id inventario %>">
  <p>
    <strong>Inventario:</strong>
    <%= inventario.inventario_id %>
  </p>

  <p>
    <strong>Existencias:</strong>
    <%= inventario.existencias %>
  </p>

  <p>
    <strong>Producto:</strong>
    <%= inventario.producto_id %>
  </p>

</div>

app/views/inventarios/edit.html.erb
<section class="py-5 mt-5">

<h1 class="display-6 fw-bold pb-md-4">Agregar existencias</h1>

<%= render "form", inventario: @inventario %>

<br>

<div>
<%= link_to 'Volver al proveedor', proveedor_path(@proveedor), class: 'btn btn-dark' %>
</div>
</section>

app/views/inventarios/index.html.erb
<section class="py-5 mt-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-6 col-md-6">
                <h1 class="display-6 fw-bold pb-md-4">Inventario</h1>
            </div>
            <div class="col-12 col-sm-6 col-md-6 text-end" style="margin-bottom: 30px;">
            <%= link_to "Productos", productos_path, class: "btn btn-primary btn-lg" %>
        </div>
        </div>
        <div data-reflow-type="product-search">
        <div class="reflow-product-search">
            <div class="ref-input-wrapper"><input id="searchInput" class="ref-search" type="text" inputmode="search" placeholder="Busca producto" /><span class="ref-cancel-search" style="display: none;"></span></div>
            <div class="ref-button" type="submit" style="display: none;">Search</div>
        </div>
        <div id="TableSorterCard" class="card">
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover" id="inventarioTable">
                            <thead class="table-dark">
                                <tr>
                                    <th scope="col">ID del inventario</th>
                                    <th scope="col">Nombre del producto</th>
                                    <th scope="col">Existencias</th>
                                    <th scope="col">ID del producto</th>
                                    <th scope="col">Proveedor</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @inventarios.each do |inventario| %>
                                <tr>
                                    <td><%= inventario.inventario_id %></td>
                                    <td><%= inventario.producto.nombre %></td>
                                    <td><%= inventario.existencias %></td>
                                    <td><%= inventario.producto.producto_id %></td>
                                    <td>
                                    <%= inventario.producto.proveedor.nombre %>        
                                    <%= inventario.producto.proveedor.apellido_paterno %>
                                    <%= inventario.producto.proveedor.apellido_materno %>
                                </td>
                                    <td><%= link_to 'Mostrar', producto_path(inventario.producto.id), class: 'btn btn-dark' %></td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    document.addEventListener('turbo:load', function() {
        const searchInput = document.getElementById('searchInput');
        const pedidosTable = document.getElementById('inventarioTable').getElementsByTagName('tbody')[0];
        const pedidos = Array.from(pedidosTable.getElementsByTagName('tr'));

        searchInput.addEventListener('input', function() {
            const searchString = searchInput.value.trim().toLowerCase();

            pedidos.forEach(function(pedido) {
                const nombreProducto = pedido.getElementsByTagName('td')[1].textContent.toLowerCase();
                const folioInventario = pedido.getElementsByTagName('td')[0].textContent.toLowerCase();
                if (nombreProducto.includes(searchString) || folioInventario.includes(searchString)) {
                    pedido.style.display = 'table-row';
                } else {
                    pedido.style.display = 'none';
                }
            });
        });
    });
</script>

app/views/inventarios/new.html.erb
<h1>New inventario</h1>

<%= render "form", inventario: @inventario %>

<br>

<div>
  <%= link_to "Back to inventarios", inventarios_path %>
</div>

app/views/inventarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inventario %>

<div>
  <%= link_to "Edit this inventario", edit_inventario_path(@inventario) %> |
  <%= link_to "Back to inventarios", inventarios_path %>

  <%= button_to "Destroy this inventario", @inventario, method: :delete %>
</div>